
aws ec2 create-vpc --instance-tenancy "default" --cidr-block "10.0.0.0/16" --tag-specifications '{"resourceType":"vpc","tags":[{"key":"Name","value":"vpc-three-tier"}]}' 
aws ec2 create-subnet --vpc-id "vpc-0faea7508614b02af" --cidr-block "10.0.1.0/24" --availability-zone-id "ilc1-az1" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"presentation-tier-1a"}]}' 
aws ec2 create-subnet --vpc-id "vpc-0faea7508614b02af" --cidr-block "10.0.2.0/24" --availability-zone-id "ilc1-az2" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"presentation-tier-1b"}]}' 
aws ec2 create-subnet --vpc-id "vpc-0faea7508614b02af" --cidr-block "10.0.3.0/24" --availability-zone-id "ilc1-az1" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"app-tier-1a"}]}' 
aws ec2 create-subnet --vpc-id "vpc-0faea7508614b02af" --cidr-block "10.0.4.0/24" --availability-zone-id "ilc1-az2" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"app-tier-1b"}]}' 
aws ec2 create-subnet --vpc-id "vpc-0faea7508614b02af" --cidr-block "10.0.5.0/24" --availability-zone-id "ilc1-az1" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"db-tier-1a"}]}' 
aws ec2 create-subnet --vpc-id "vpc-0faea7508614b02af" --cidr-block "10.0.6.0/24" --availability-zone-id "ilc1-az2" --tag-specifications '{"resourceType":"subnet","tags":[{"key":"Name","value":"db-tier-1b"}]}' 
aws ec2 modify-vpc-attribute --enable-dns-hostnames '{"value":true}' --vpc-id "vpc-0faea7508614b02af" 
aws ec2 modify-subnet-attribute --subnet-id "subnet-06264c0973a483db0" --map-public-ip-on-launch '{"value":true}' 
aws ec2 modify-subnet-attribute --subnet-id "subnet-0e335b1e1706d9cec" --map-public-ip-on-launch '{"value":true}' 
aws ec2 create-internet-gateway --tag-specifications '{"resourceType":"internet-gateway","tags":[{"key":"Name","value":"igw-three-tier"}]}' 
aws ec2 attach-internet-gateway --vpc-id "vpc-0faea7508614b02af" --internet-gateway-id "igw-0b0857ce01c6ef97e" 
aws ec2 allocate-address --domain "vpc" --network-border-group "il-central-1" 
aws ec2 create-nat-gateway --subnet-id "subnet-06264c0973a483db0" --allocation-id "eipalloc-07a036cb991bcb394" --tag-specifications '{"resourceType":"natgateway","tags":[{"key":"Name","value":"nat-three-tier"}]}' --connectivity-type "public" --client-token "aae5093e-315a-4e04-85cd-c9a11cbdf346" 
aws ec2 create-route-table --vpc-id "vpc-0faea7508614b02af" --tag-specifications '{"resourceType":"route-table","tags":[{"key":"Name","value":"rt-presentation-tier"}]}' 
aws ec2 create-route-table --vpc-id "vpc-0faea7508614b02af" --tag-specifications '{"resourceType":"route-table","tags":[{"key":"Name","value":"rt-app-tier"}]}' 
aws ec2 create-route-table --vpc-id "vpc-0faea7508614b02af" --tag-specifications '{"resourceType":"route-table","tags":[{"key":"Name","value":"rt-db-tier"}]}' 
aws ec2 create-route --route-table-id "rtb-06ddf9b6e3c74c81f" --destination-cidr-block "0.0.0.0/0" --nat-gateway-id "nat-09f88a4297a5bbdf4" 
aws ec2 create-route --route-table-id "rtb-0e1124cf02a34160e" --destination-cidr-block "0.0.0.0/0" --gateway-id "igw-0b0857ce01c6ef97e" 
aws ec2 run-instances --image-id "ami-01a897cd16ace0aa7" --instance-type "t3.micro" --key-name "practice" --network-interfaces '{"SubnetId":"subnet-06264c0973a483db0","AssociatePublicIpAddress":true,"DeviceIndex":0,"Groups":["sg-061af008d41fcdbf6"]}' --credit-specification '{"CpuCredits":"unlimited"}' --tag-specifications '{"ResourceType":"instance","Tags":[{"Key":"Name","Value":"public"}]}' --metadata-options '{"HttpEndpoint":"enabled","HttpPutResponseHopLimit":2,"HttpTokens":"required"}' --private-dns-name-options '{"HostnameType":"ip-name","EnableResourceNameDnsARecord":false,"EnableResourceNameDnsAAAARecord":false}' --count "1" 
aws ec2 run-instances --image-id "ami-01a897cd16ace0aa7" --instance-type "t3.micro" --key-name "practice" --network-interfaces '{"SubnetId":"subnet-06264c0973a483db0","AssociatePublicIpAddress":true,"DeviceIndex":0,"Groups":["sg-061af008d41fcdbf6"]}' --credit-specification '{"CpuCredits":"unlimited"}' --tag-specifications '{"ResourceType":"instance","Tags":[{"Key":"Name","Value":"public"}]}' --metadata-options '{"HttpEndpoint":"enabled","HttpPutResponseHopLimit":2,"HttpTokens":"required"}' --private-dns-name-options '{"HostnameType":"ip-name","EnableResourceNameDnsARecord":false,"EnableResourceNameDnsAAAARecord":false}' --count "1" 
aws ec2 run-instances --image-id "ami-01a897cd16ace0aa7" --instance-type "t3.micro" --key-name "practice" --network-interfaces '{"SubnetId":"subnet-0c922819205861f77","AssociatePublicIpAddress":false,"DeviceIndex":0,"Groups":["sg-076fad45037e9e5a6"]}' --credit-specification '{"CpuCredits":"unlimited"}' --tag-specifications '{"ResourceType":"instance","Tags":[{"Key":"Name","Value":"app-ec2"}]}' --metadata-options '{"HttpEndpoint":"enabled","HttpPutResponseHopLimit":2,"HttpTokens":"required"}' --private-dns-name-options '{"HostnameType":"ip-name","EnableResourceNameDnsARecord":false,"EnableResourceNameDnsAAAARecord":false}' --count "1" 
aws ec2 run-instances --image-id "ami-01a897cd16ace0aa7" --instance-type "t3.micro" --key-name "practice" --network-interfaces '{"SubnetId":"subnet-0b0ee136924f38e1b","AssociatePublicIpAddress":false,"DeviceIndex":0,"Groups":["sg-012cf3a495334916b"]}' --credit-specification '{"CpuCredits":"unlimited"}' --tag-specifications '{"ResourceType":"instance","Tags":[{"Key":"Name","Value":"db"}]}' --metadata-options '{"HttpEndpoint":"enabled","HttpPutResponseHopLimit":2,"HttpTokens":"required"}' --private-dns-name-options '{"HostnameType":"ip-name","EnableResourceNameDnsARecord":false,"EnableResourceNameDnsAAAARecord":false}' --count "1" 
